// checkpoint-data.ts
// Source: ICA_VSB_Tuas & Woodlands_BOQ_R9_CAA 21012026 (2)
// 60 total locations: 32 Tuas + 28 Woodlands
// SVG coordinate space: 0-1000 (viewBox "0 0 1000 800")

export type EquipmentType =
  | "blocker"
  | "k12-fixed-bollard"
  | "k12-auto-bollard"
  | "k12-dab"
  | "road-hump"
  | "traffic-light"
  | "sliding-bollard"
  | "non-crash-barrier"
  | "auto-bollard"
  | "crash-barrier";

export interface EquipmentLocation {
  sn: number;
  mapRef: string;
  lanes: string[];
  type: EquipmentType;
  direction: string;
  laneWidth: number;
  cctv: "Y" | "N" | "E";
  cctvPink: number;
  cctvGreen: number;
  installLocation: "Ground" | "Bridge" | "Building";
  vehicleType: string;
  remarks: string;
  x: number;
  y: number;
}

export interface CheckpointData {
  id: "tuas" | "woodlands";
  name: string;
  locations: EquipmentLocation[];
  totalEquipment: number;
  totalCCTV: number;
}

// ─── TUAS CHECKPOINT ──────────────────────────────────────────────────────────
// Layout: Oval compound, horizontal orientation
// JB approach from LEFT (x: 50-200), SG approach from RIGHT (x: 800-950)
// Compound center ~(500, 400), rx:380, ry:260
// S/N 1-20: Ground level — perimeter roads (clockwise)
// S/N 21-32: Bridge/Level 3 — LEFT side bridge approach

const tuasLocations: EquipmentLocation[] = [
  // S/N 1 — Map 1E — CP→SG exit road (bottom-right area)
  {
    sn: 1,
    mapRef: "1E",
    lanes: ["A", "B"],
    type: "blocker",
    direction: "CP → SG",
    laneWidth: 3.8,
    cctv: "Y",
    cctvPink: 2,
    cctvGreen: 2,
    installLocation: "Ground",
    vehicleType: "Lorry",
    remarks: "Side Gap 1m (R) Lane A; Side Gap 1m (L) Lane B",
    x: 840,
    y: 400,
  },
  // S/N 2 — Map 2 — CP→SG (Bus)
  {
    sn: 2,
    mapRef: "2",
    lanes: ["A", "B"],
    type: "road-hump",
    direction: "CP → SG",
    laneWidth: 4.0,
    cctv: "N",
    cctvPink: 0,
    cctvGreen: 0,
    installLocation: "Ground",
    vehicleType: "Bus",
    remarks: "Gate Normally Closed",
    x: 820,
    y: 340,
  },
  // S/N 3 — Map 3 — Within Building
  {
    sn: 3,
    mapRef: "3",
    lanes: ["A"],
    type: "road-hump",
    direction: "Within Building",
    laneWidth: 7.2,
    cctv: "N",
    cctvPink: 0,
    cctvGreen: 0,
    installLocation: "Building",
    vehicleType: "Lorry/Bus",
    remarks: "Gate Normally Closed",
    x: 520,
    y: 360,
  },
  // S/N 4 — Map 5E — SG↔CP (2-way, 3 lanes)
  {
    sn: 4,
    mapRef: "5E",
    lanes: ["A", "B", "C"],
    type: "blocker",
    direction: "SG ↔ CP (2W)",
    laneWidth: 4.1,
    cctv: "Y",
    cctvPink: 2,
    cctvGreen: 2,
    installLocation: "Ground",
    vehicleType: "Lorry/Car",
    remarks: "Side Gap 2m (R) Lane B",
    x: 800,
    y: 460,
  },
  // S/N 5 — Map 6E — SG→CP (Car/Motorcycle)
  {
    sn: 5,
    mapRef: "6E",
    lanes: ["A"],
    type: "blocker",
    direction: "SG → CP",
    laneWidth: 4.5,
    cctv: "Y",
    cctvPink: 2,
    cctvGreen: 2,
    installLocation: "Ground",
    vehicleType: "Car/Motorcycle",
    remarks: "Side Gap 1m (R)",
    x: 760,
    y: 510,
  },
  // S/N 6 — Map 7 — SG→CP (Car)
  {
    sn: 6,
    mapRef: "7",
    lanes: ["A"],
    type: "road-hump",
    direction: "SG → CP",
    laneWidth: 4.4,
    cctv: "N",
    cctvPink: 0,
    cctvGreen: 0,
    installLocation: "Ground",
    vehicleType: "Car",
    remarks: "Gate Normally Closed",
    x: 720,
    y: 555,
  },
  // S/N 7 — Map 4 — Within Building
  {
    sn: 7,
    mapRef: "4",
    lanes: ["A"],
    type: "road-hump",
    direction: "Within Building",
    laneWidth: 8.5,
    cctv: "N",
    cctvPink: 0,
    cctvGreen: 0,
    installLocation: "Building",
    vehicleType: "Lorry/Bus/Car",
    remarks: "Gate Normally Closed",
    x: 560,
    y: 420,
  },
  // S/N 8 — Map 8 — SG→CP (Bus)
  {
    sn: 8,
    mapRef: "8",
    lanes: ["A"],
    type: "road-hump",
    direction: "SG → CP",
    laneWidth: 8.0,
    cctv: "N",
    cctvPink: 0,
    cctvGreen: 0,
    installLocation: "Ground",
    vehicleType: "Bus",
    remarks: "Gate Normally Closed. Suggest Road Blocker since Entrance",
    x: 680,
    y: 580,
  },
  // S/N 9 — Map 9E — SG→CP (Lorry, 3 lanes)
  {
    sn: 9,
    mapRef: "9E",
    lanes: ["A", "B", "C"],
    type: "blocker",
    direction: "SG → CP",
    laneWidth: 3.5,
    cctv: "Y",
    cctvPink: 2,
    cctvGreen: 2,
    installLocation: "Ground",
    vehicleType: "Lorry",
    remarks: "Side Gap 2.1m (R) Lane A",
    x: 630,
    y: 605,
  },
  // S/N 10 — Map 11E — Within Building (Office)
  {
    sn: 10,
    mapRef: "11E",
    lanes: ["A"],
    type: "blocker",
    direction: "Within Building",
    laneWidth: 7.0,
    cctv: "Y",
    cctvPink: 1,
    cctvGreen: 1,
    installLocation: "Building",
    vehicleType: "Lorry",
    remarks: "Not OP — Office. Side Gap 2.1m (R), 1m (L)",
    x: 500,
    y: 480,
  },
  // S/N 11 — Map 10A — CP→JB (K12 Drop Arm Barrier)
  {
    sn: 11,
    mapRef: "10A",
    lanes: ["A"],
    type: "k12-dab",
    direction: "CP → JB",
    laneWidth: 7.5,
    cctv: "Y",
    cctvPink: 0,
    cctvGreen: 1,
    installLocation: "Ground",
    vehicleType: "Lorry",
    remarks: "Not OP — Building. Gate Normally Closed",
    x: 340,
    y: 580,
  },
  // S/N 12 — Map 14E — Within Building (Office)
  {
    sn: 12,
    mapRef: "14E",
    lanes: ["A"],
    type: "blocker",
    direction: "Within Building",
    laneWidth: 7.0,
    cctv: "Y",
    cctvPink: 1,
    cctvGreen: 1,
    installLocation: "Building",
    vehicleType: "Lorry",
    remarks: "Not OP — Office. Side Gap 2m (R), 2m (L)",
    x: 460,
    y: 460,
  },
  // S/N 13 — Map 15A — Within Building (Retractable + Fixed Bollards)
  {
    sn: 13,
    mapRef: "15A",
    lanes: ["A"],
    type: "auto-bollard",
    direction: "Within Building",
    laneWidth: 13.0,
    cctv: "N",
    cctvPink: 0,
    cctvGreen: 0,
    installLocation: "Building",
    vehicleType: "Lorry",
    remarks: "Retractable + Fixed Bollards + 4x Loop Sensor. Side Gap 7.8m (R), 11.5m (L)",
    x: 430,
    y: 440,
  },
  // S/N 14 — Map 37 — JB→CP (Lorry, 2 lanes)
  {
    sn: 14,
    mapRef: "37",
    lanes: ["A", "B"],
    type: "blocker",
    direction: "JB → CP",
    laneWidth: 4.6,
    cctv: "Y",
    cctvPink: 2,
    cctvGreen: 2,
    installLocation: "Ground",
    vehicleType: "Lorry",
    remarks: "Side Gap 30.4m (L) Lane B",
    x: 280,
    y: 540,
  },
  // S/N 15 — Map 16A — JB→CP (Lorry)
  {
    sn: 15,
    mapRef: "16A",
    lanes: ["A"],
    type: "blocker",
    direction: "JB → CP",
    laneWidth: 7.4,
    cctv: "Y",
    cctvPink: 1,
    cctvGreen: 1,
    installLocation: "Ground",
    vehicleType: "Lorry",
    remarks: "Gate Normally Open. Side Gap 1.5m (×2)",
    x: 230,
    y: 500,
  },
  // S/N 16 — Map 38 — JB→CP (Lorry, Office)
  {
    sn: 16,
    mapRef: "38",
    lanes: ["A"],
    type: "blocker",
    direction: "JB → CP",
    laneWidth: 7.3,
    cctv: "Y",
    cctvPink: 1,
    cctvGreen: 1,
    installLocation: "Ground",
    vehicleType: "Lorry",
    remarks: "Not OP — Office. Side Gap 2m (R), 2m (L)",
    x: 200,
    y: 450,
  },
  // S/N 17 — Map 25 — Within Building (Bus)
  {
    sn: 17,
    mapRef: "25",
    lanes: ["A"],
    type: "road-hump",
    direction: "Within Building",
    laneWidth: 7.3,
    cctv: "N",
    cctvPink: 0,
    cctvGreen: 0,
    installLocation: "Building",
    vehicleType: "Bus",
    remarks: "Gate Normally Closed",
    x: 540,
    y: 390,
  },
  // S/N 18 — Map 23 — Within Building (Bus)
  {
    sn: 18,
    mapRef: "23",
    lanes: ["A"],
    type: "road-hump",
    direction: "Within Building",
    laneWidth: 5.6,
    cctv: "N",
    cctvPink: 0,
    cctvGreen: 0,
    installLocation: "Building",
    vehicleType: "Bus",
    remarks: "Gate Normally Closed",
    x: 490,
    y: 370,
  },
  // S/N 19 — Map 24 — Within Building (Bus)
  {
    sn: 19,
    mapRef: "24",
    lanes: ["A"],
    type: "road-hump",
    direction: "Within Building",
    laneWidth: 5.6,
    cctv: "N",
    cctvPink: 0,
    cctvGreen: 0,
    installLocation: "Building",
    vehicleType: "Bus",
    remarks: "Gate Normally Closed",
    x: 510,
    y: 350,
  },
  // S/N 20 — Map 26 — Within Building (Bus, RCP)
  {
    sn: 20,
    mapRef: "26",
    lanes: ["RCP"],
    type: "road-hump",
    direction: "Within Building",
    laneWidth: 5.7,
    cctv: "N",
    cctvPink: 0,
    cctvGreen: 0,
    installLocation: "Building",
    vehicleType: "Bus",
    remarks: "Gate Normally Closed",
    x: 470,
    y: 390,
  },
  // S/N 21 — Map 13E — CP→JB Bridge (Lorry+Bus, 2 lanes)
  {
    sn: 21,
    mapRef: "13E",
    lanes: ["A", "B"],
    type: "blocker",
    direction: "CP → JB",
    laneWidth: 4.1,
    cctv: "Y",
    cctvPink: 2,
    cctvGreen: 2,
    installLocation: "Bridge",
    vehicleType: "Lorry/Bus",
    remarks: "",
    x: 160,
    y: 310,
  },
  // S/N 22 — Map 13R — CP→JB Bridge (Lorry+Bus, 2 lanes)
  {
    sn: 22,
    mapRef: "13R",
    lanes: ["A", "B"],
    type: "blocker",
    direction: "CP → JB",
    laneWidth: 4.1,
    cctv: "Y",
    cctvPink: 1,
    cctvGreen: 0,
    installLocation: "Bridge",
    vehicleType: "Lorry/Bus",
    remarks: "",
    x: 160,
    y: 355,
  },
  // S/N 23 — Map 36 Lvl3 — JB→CP Bridge (Car/Motorcycle, 3 lanes)
  {
    sn: 23,
    mapRef: "36 Lvl3",
    lanes: ["A", "B", "C"],
    type: "blocker",
    direction: "JB → CP",
    laneWidth: 3.0,
    cctv: "Y",
    cctvPink: 2,
    cctvGreen: 2,
    installLocation: "Bridge",
    vehicleType: "Car/Motorcycle",
    remarks: "",
    x: 130,
    y: 265,
  },
  // S/N 24 — Map 35 Lvl3 — CP→JB Bridge (Car, 2 lanes — Existing CCTV)
  {
    sn: 24,
    mapRef: "35 Lvl3",
    lanes: ["A", "B"],
    type: "blocker",
    direction: "CP → JB",
    laneWidth: 5.0,
    cctv: "E",
    cctvPink: 2,
    cctvGreen: 2,
    installLocation: "Bridge",
    vehicleType: "Car",
    remarks: "2 Existing CCTV per lane",
    x: 130,
    y: 220,
  },
  // S/N 25 — Map 34 Lvl3 — JB→CP Bridge (Sliding Bollards)
  {
    sn: 25,
    mapRef: "34 Lvl3",
    lanes: ["A"],
    type: "sliding-bollard",
    direction: "JB → CP",
    laneWidth: 6.6,
    cctv: "N",
    cctvPink: 0,
    cctvGreen: 0,
    installLocation: "Bridge",
    vehicleType: "Car/Motorcycle",
    remarks: "Gate Normally Closed",
    x: 100,
    y: 175,
  },
  // S/N 26 — Map 33 Lvl3 — CP→JB Bridge (Road Hump)
  {
    sn: 26,
    mapRef: "33 Lvl3",
    lanes: ["A"],
    type: "road-hump",
    direction: "CP → JB",
    laneWidth: 6.7,
    cctv: "N",
    cctvPink: 0,
    cctvGreen: 0,
    installLocation: "Bridge",
    vehicleType: "Car/Motorcycle",
    remarks: "Gate Normally Closed",
    x: 100,
    y: 135,
  },
  // S/N 27 — Map 31 Lvl3 — Within Building (Sliding Bollard, Car)
  {
    sn: 27,
    mapRef: "31 Lvl3",
    lanes: ["A"],
    type: "sliding-bollard",
    direction: "Within Building",
    laneWidth: 7.0,
    cctv: "Y",
    cctvPink: 2,
    cctvGreen: 0,
    installLocation: "Building",
    vehicleType: "Car",
    remarks: "Gate Normally Closed",
    x: 200,
    y: 170,
  },
  // S/N 28 — Map 32 Lvl3 — Within Building (Road Hump / Drop Arm)
  {
    sn: 28,
    mapRef: "32 Lvl3",
    lanes: ["A"],
    type: "k12-dab",
    direction: "Within Building",
    laneWidth: 6.8,
    cctv: "N",
    cctvPink: 0,
    cctvGreen: 0,
    installLocation: "Bridge",
    vehicleType: "Car",
    remarks: "Road Hump / Drop Arm barrier — dual proposal",
    x: 200,
    y: 215,
  },
  // S/N 29 — Map 30 Lvl3 — CP→SG Bridge (Road Hump, Car/Motorcycle)
  {
    sn: 29,
    mapRef: "30 Lvl3",
    lanes: ["A"],
    type: "road-hump",
    direction: "CP → SG",
    laneWidth: 6.7,
    cctv: "N",
    cctvPink: 0,
    cctvGreen: 0,
    installLocation: "Bridge",
    vehicleType: "Car/Motorcycle",
    remarks: "Gate Normally Closed",
    x: 250,
    y: 260,
  },
  // S/N 30 — Map 27 Lvl3 — CP→SG Bridge (Blocker, Motorcycle+Car, 3 lanes)
  {
    sn: 30,
    mapRef: "27 Lvl3",
    lanes: ["A", "B", "C"],
    type: "blocker",
    direction: "CP → SG",
    laneWidth: 3.6,
    cctv: "Y",
    cctvPink: 2,
    cctvGreen: 2,
    installLocation: "Bridge",
    vehicleType: "Motorcycle/Car",
    remarks: "",
    x: 250,
    y: 310,
  },
  // S/N 31 — Map 28 Lvl3 — SG→CP Bridge (Blocker, Motorcycle+Car, 3 lanes)
  {
    sn: 31,
    mapRef: "28 Lvl3",
    lanes: ["A", "B", "C"],
    type: "blocker",
    direction: "SG → CP",
    laneWidth: 3.6,
    cctv: "Y",
    cctvPink: 2,
    cctvGreen: 2,
    installLocation: "Bridge",
    vehicleType: "Motorcycle/Car",
    remarks: "Side Gap 0.5m (R) Lane A; Side Gap 0.5m (L) Lane C",
    x: 250,
    y: 355,
  },
  // S/N 32 — Map 29 Lvl3 — 1W Bridge (Road Hump, Car/Motorcycle)
  {
    sn: 32,
    mapRef: "29 Lvl3",
    lanes: ["A"],
    type: "road-hump",
    direction: "1W",
    laneWidth: 6.7,
    cctv: "N",
    cctvPink: 0,
    cctvGreen: 0,
    installLocation: "Bridge",
    vehicleType: "Car/Motorcycle",
    remarks: "Gate Normally Closed",
    x: 300,
    y: 260,
  },
];

// ─── WOODLANDS CHECKPOINT ─────────────────────────────────────────────────────
// Layout: Trapezoid/wedge — wider at TOP (JB/north), narrower at BOTTOM (SG)
// JB approach from TOP (y: 50-200), SG exit at BOTTOM (y: 650-780)
// Compound: Top edge x:100-900 at y=120, Bottom edge x:250-750 at y=700
// Car lanes: center-left, Bus lanes: center, Lorry lanes: center-right
// Bridge entries (S/N 4,7,9,11,12,27,28): LEFT/RIGHT edges

const woodlandsLocations: EquipmentLocation[] = [
  // S/N 1 — Map 2 — JB→CP (Car/Motorbike, 3 lanes)
  {
    sn: 1,
    mapRef: "2",
    lanes: ["A", "B", "C"],
    type: "blocker",
    direction: "JB → CP",
    laneWidth: 3.8,
    cctv: "Y",
    cctvPink: 3,
    cctvGreen: 3,
    installLocation: "Ground",
    vehicleType: "Car/Motorbike",
    remarks: "Peak hour sometimes open to motor lane",
    x: 310,
    y: 155,
  },
  // S/N 2 — Map 3 — JB→CP (Car, 2 lanes)
  {
    sn: 2,
    mapRef: "3",
    lanes: ["A", "B"],
    type: "blocker",
    direction: "JB → CP",
    laneWidth: 5.5,
    cctv: "Y",
    cctvPink: 2,
    cctvGreen: 2,
    installLocation: "Ground",
    vehicleType: "Car",
    remarks: "Split to 2 lanes (3m ea); normally 1 lane closed",
    x: 410,
    y: 145,
  },
  // S/N 3 — Map 4 — CP→JB (Car, 2 lanes — U-turn)
  {
    sn: 3,
    mapRef: "4",
    lanes: ["A", "B"],
    type: "blocker",
    direction: "CP → JB",
    laneWidth: 3.6,
    cctv: "Y",
    cctvPink: 2,
    cctvGreen: 2,
    installLocation: "Ground",
    vehicleType: "Car",
    remarks: "U-turn lane to JB, normally closed",
    x: 510,
    y: 145,
  },
  // S/N 4 — Map 19 — JB→CP Bridge (Bus, 2 lanes)
  {
    sn: 4,
    mapRef: "19",
    lanes: ["A", "B"],
    type: "blocker",
    direction: "JB → CP",
    laneWidth: 3.5,
    cctv: "Y",
    cctvPink: 2,
    cctvGreen: 2,
    installLocation: "Bridge",
    vehicleType: "Bus",
    remarks: "Bus lane into CP",
    x: 160,
    y: 200,
  },
  // S/N 5 — Map 21 — JB→CP Ground (Lorry, 2 lanes)
  {
    sn: 5,
    mapRef: "21",
    lanes: ["A", "B"],
    type: "blocker",
    direction: "JB → CP",
    laneWidth: 3.5,
    cctv: "Y",
    cctvPink: 2,
    cctvGreen: 2,
    installLocation: "Ground",
    vehicleType: "Lorry",
    remarks: "Lorry into CP",
    x: 660,
    y: 165,
  },
  // S/N 6 — Map 20 — CP→JB Ground (Lorry, 2 lanes)
  {
    sn: 6,
    mapRef: "20",
    lanes: ["A", "B"],
    type: "blocker",
    direction: "CP → JB",
    laneWidth: 2.85,
    cctv: "Y",
    cctvPink: 2,
    cctvGreen: 2,
    installLocation: "Ground",
    vehicleType: "Lorry",
    remarks: "Lorry out to JB",
    x: 730,
    y: 185,
  },
  // S/N 7 — Map 18 — CP→JB Bridge (Bus, 2 lanes)
  {
    sn: 7,
    mapRef: "18",
    lanes: ["A", "B"],
    type: "blocker",
    direction: "CP → JB",
    laneWidth: 3.6,
    cctv: "Y",
    cctvPink: 2,
    cctvGreen: 2,
    installLocation: "Bridge",
    vehicleType: "Bus",
    remarks: "Bus out to JB. Existing road hump",
    x: 160,
    y: 265,
  },
  // S/N 8 — Map 16 — CP→JB Ground (Car/Motorbike, 2 lanes)
  {
    sn: 8,
    mapRef: "16",
    lanes: ["A", "B"],
    type: "blocker",
    direction: "CP → JB",
    laneWidth: 3.75,
    cctv: "Y",
    cctvPink: 2,
    cctvGreen: 2,
    installLocation: "Ground",
    vehicleType: "Car/Motorbike",
    remarks: "",
    x: 250,
    y: 215,
  },
  // S/N 9 — Map 13 — SG→CP Bridge (Motor+Car, 4 lanes)
  {
    sn: 9,
    mapRef: "13",
    lanes: ["A", "B", "C", "D"],
    type: "blocker",
    direction: "SG → CP",
    laneWidth: 3.25,
    cctv: "Y",
    cctvPink: 4,
    cctvGreen: 4,
    installLocation: "Bridge",
    vehicleType: "Car/Motor",
    remarks: "",
    x: 840,
    y: 295,
  },
  // S/N 10 — Map 29 — SG→CP Ground (Lorry, 2 lanes)
  {
    sn: 10,
    mapRef: "29",
    lanes: ["A", "B"],
    type: "blocker",
    direction: "SG → CP",
    laneWidth: 3.0,
    cctv: "Y",
    cctvPink: 2,
    cctvGreen: 2,
    installLocation: "Ground",
    vehicleType: "Lorry",
    remarks: "Lorry into CP",
    x: 730,
    y: 310,
  },
  // S/N 11 — Map 30 — SG→CP Bridge (Bus, 2 lanes)
  {
    sn: 11,
    mapRef: "30",
    lanes: ["A", "B"],
    type: "blocker",
    direction: "SG → CP",
    laneWidth: 3.0,
    cctv: "Y",
    cctvPink: 2,
    cctvGreen: 2,
    installLocation: "Bridge",
    vehicleType: "Bus",
    remarks: "Side gap 1.2m (R) Lane A",
    x: 840,
    y: 355,
  },
  // S/N 12 — Map 27 — CP→SG Bridge (Bus, 2 lanes)
  {
    sn: 12,
    mapRef: "27",
    lanes: ["A", "B"],
    type: "blocker",
    direction: "CP → SG",
    laneWidth: 3.0,
    cctv: "Y",
    cctvPink: 2,
    cctvGreen: 2,
    installLocation: "Bridge",
    vehicleType: "Bus",
    remarks: "Bus out to SG",
    x: 840,
    y: 415,
  },
  // S/N 13 — Map 28 — CP→SG Ground (Lorry, 2 lanes)
  {
    sn: 13,
    mapRef: "28",
    lanes: ["A", "B"],
    type: "blocker",
    direction: "CP → SG",
    laneWidth: 3.0,
    cctv: "Y",
    cctvPink: 2,
    cctvGreen: 2,
    installLocation: "Ground",
    vehicleType: "Lorry",
    remarks: "Side gap 2m (R)",
    x: 730,
    y: 395,
  },
  // S/N 14 — Map 28R — CP→SG Ground (Bus Crash Barrier)
  {
    sn: 14,
    mapRef: "28R",
    lanes: ["A"],
    type: "crash-barrier",
    direction: "CP → SG",
    laneWidth: 6.0,
    cctv: "Y",
    cctvPink: 1,
    cctvGreen: 1,
    installLocation: "Ground",
    vehicleType: "Lorry",
    remarks: "Side gap 2m (R)",
    x: 690,
    y: 440,
  },
  // S/N 15 — Map 10 — CP→SG Ground (Car/Motorbike, space constraint)
  {
    sn: 15,
    mapRef: "10",
    lanes: ["A"],
    type: "blocker",
    direction: "CP → SG",
    laneWidth: 5.0,
    cctv: "Y",
    cctvPink: 1,
    cctvGreen: 1,
    installLocation: "Ground",
    vehicleType: "Car/Motorbike",
    remarks: "Space constraint — install on ramp. 2 lanes merge to 1",
    x: 400,
    y: 640,
  },
  // S/N 16 — Map 11 — CP→SG Ground (Car, space constraint)
  {
    sn: 16,
    mapRef: "11",
    lanes: ["A"],
    type: "blocker",
    direction: "CP → SG",
    laneWidth: 6.0,
    cctv: "Y",
    cctvPink: 1,
    cctvGreen: 1,
    installLocation: "Ground",
    vehicleType: "Car",
    remarks: "Space constraint — install on ramp",
    x: 460,
    y: 660,
  },
  // S/N 17 — Map 9 — CP→SG Ground (Car/Motorbike, space constraint)
  {
    sn: 17,
    mapRef: "9",
    lanes: ["A"],
    type: "blocker",
    direction: "CP → SG",
    laneWidth: 5.0,
    cctv: "Y",
    cctvPink: 1,
    cctvGreen: 1,
    installLocation: "Ground",
    vehicleType: "Car/Motorbike",
    remarks: "Space constraint — install on ramp. 2 lanes merge to 1",
    x: 350,
    y: 640,
  },
  // S/N 18 — Map 12 — 2W Staff Lane (Car/Motorbike)
  {
    sn: 18,
    mapRef: "12",
    lanes: ["A"],
    type: "blocker",
    direction: "2W staff lane",
    laneWidth: 4.0,
    cctv: "Y",
    cctvPink: 1,
    cctvGreen: 1,
    installLocation: "Ground",
    vehicleType: "Car/Motorbike",
    remarks: "Staff lane out to SG. 2W. Existing card reader ×2",
    x: 540,
    y: 645,
  },
  // S/N 19 — Map 8 — SG→CP Ground (Car/Motorbike, 2W)
  {
    sn: 19,
    mapRef: "8",
    lanes: ["A"],
    type: "blocker",
    direction: "SG → CP",
    laneWidth: 5.8,
    cctv: "Y",
    cctvPink: 1,
    cctvGreen: 1,
    installLocation: "Ground",
    vehicleType: "Car/Motorbike",
    remarks: "U-turn possible. 2W. Card reader ×2, ISS sensor ×4",
    x: 600,
    y: 625,
  },
  // S/N 20 — Map 25 — Within Building (Lorry, 2 lanes)
  {
    sn: 20,
    mapRef: "25",
    lanes: ["A", "B"],
    type: "blocker",
    direction: "Within Building",
    laneWidth: 4.0,
    cctv: "Y",
    cctvPink: 2,
    cctvGreen: 2,
    installLocation: "Building",
    vehicleType: "Lorry",
    remarks: "ICA card access system (Darren)",
    x: 430,
    y: 490,
  },
  // S/N 21 — Map 26 — Within Building (Lorry)
  {
    sn: 21,
    mapRef: "26",
    lanes: ["A"],
    type: "blocker",
    direction: "Within Building",
    laneWidth: 6.0,
    cctv: "Y",
    cctvPink: 1,
    cctvGreen: 1,
    installLocation: "Building",
    vehicleType: "Lorry",
    remarks: "ICA card access system (Darren)",
    x: 500,
    y: 490,
  },
  // S/N 22 — Map 14 — Staff Parking (Car/Motorbike, 2 lanes)
  {
    sn: 22,
    mapRef: "14",
    lanes: ["A", "B"],
    type: "blocker",
    direction: "SG → CP / CP → SG",
    laneWidth: 3.95,
    cctv: "Y",
    cctvPink: 2,
    cctvGreen: 2,
    installLocation: "Ground",
    vehicleType: "Car/Motorbike",
    remarks: "Staff parking",
    x: 640,
    y: 560,
  },
  // S/N 23 — Map 24 — JB→CP Auto Bollard (Lorry, 2 lanes)
  {
    sn: 23,
    mapRef: "24",
    lanes: ["A", "B"],
    type: "auto-bollard",
    direction: "JB → CP",
    laneWidth: 4.0,
    cctv: "Y",
    cctvPink: 2,
    cctvGreen: 2,
    installLocation: "Building",
    vehicleType: "Lorry",
    remarks: "Lorry U-turn possible. 2W",
    x: 430,
    y: 545,
  },
  // S/N 24 — Map 23 — JB→CP Auto Bollard (Lorry, 2 lanes)
  {
    sn: 24,
    mapRef: "23",
    lanes: ["A", "B"],
    type: "auto-bollard",
    direction: "JB → CP",
    laneWidth: 4.0,
    cctv: "Y",
    cctvPink: 2,
    cctvGreen: 2,
    installLocation: "Building",
    vehicleType: "Lorry",
    remarks: "Lorry U-turn possible. 2W",
    x: 500,
    y: 545,
  },
  // S/N 25 — Map 23R — CP→JB K12 DAB / Blocker (Lorry/Car)
  {
    sn: 25,
    mapRef: "23R",
    lanes: ["A"],
    type: "k12-dab",
    direction: "CP → JB",
    laneWidth: 6.8,
    cctv: "Y",
    cctvPink: 1,
    cctvGreen: 1,
    installLocation: "Building",
    vehicleType: "Lorry/Car",
    remarks: "Proposed K12 DAB/Blocker. Open to cars during peak hour",
    x: 570,
    y: 545,
  },
  // S/N 26 — Map 17 — 2W Car/Motorbike (U-turn to SG)
  {
    sn: 26,
    mapRef: "17",
    lanes: ["A"],
    type: "blocker",
    direction: "2W",
    laneWidth: 4.0,
    cctv: "Y",
    cctvPink: 1,
    cctvGreen: 1,
    installLocation: "Ground",
    vehicleType: "Car/Motorbike",
    remarks: "Car U-turn to SG lane",
    x: 640,
    y: 480,
  },
  // S/N 27 — Map 38R(A) Lvl2 — CP→JB Sliding Bollard Bridge (Bus)
  {
    sn: 27,
    mapRef: "38R(A) Lvl2",
    lanes: ["A"],
    type: "sliding-bollard",
    direction: "CP → JB",
    laneWidth: 7.3,
    cctv: "E",
    cctvPink: 0,
    cctvGreen: 0,
    installLocation: "Bridge",
    vehicleType: "Bus",
    remarks: "Bus to JB. Bollard run 23m + 10.2m from bus bay",
    x: 170,
    y: 430,
  },
  // S/N 28 — Map 39R(A) Lvl2 — CP→SG Sliding Bollard Bridge (Bus)
  {
    sn: 28,
    mapRef: "39R(A) Lvl2",
    lanes: ["A"],
    type: "sliding-bollard",
    direction: "CP → SG",
    laneWidth: 7.4,
    cctv: "E",
    cctvPink: 0,
    cctvGreen: 0,
    installLocation: "Bridge",
    vehicleType: "Bus",
    remarks: "Bus to SG. Space constraint. Existing road ramp",
    x: 170,
    y: 490,
  },
];

// ─── CHECKPOINT DATA EXPORTS ──────────────────────────────────────────────────

export const tuasCheckpoint: CheckpointData = {
  id: "tuas",
  name: "Tuas Checkpoint",
  locations: tuasLocations,
  totalEquipment: tuasLocations.length,
  totalCCTV: tuasLocations.filter((l) => l.cctv === "Y" || l.cctv === "E").length,
};

export const woodlandsCheckpoint: CheckpointData = {
  id: "woodlands",
  name: "Woodlands Checkpoint",
  locations: woodlandsLocations,
  totalEquipment: woodlandsLocations.length,
  totalCCTV: woodlandsLocations.filter((l) => l.cctv === "Y" || l.cctv === "E").length,
};

export const checkpoints: CheckpointData[] = [tuasCheckpoint, woodlandsCheckpoint];

// ─── EQUIPMENT COLOR MAP ──────────────────────────────────────────────────────

export const EQUIPMENT_COLORS: Record<EquipmentType, string> = {
  blocker: "#2F5FD0",
  "k12-fixed-bollard": "#6B7280",
  "k12-auto-bollard": "#06B6D4",
  "k12-dab": "#F59E0B",
  "road-hump": "#EAB308",
  "traffic-light": "#22C55E",
  "sliding-bollard": "#8B5CF6",
  "non-crash-barrier": "#64748B",
  "auto-bollard": "#06B6D4",
  "crash-barrier": "#EF4444",
};

export const EQUIPMENT_LABELS: Record<EquipmentType, string> = {
  blocker: "Blocker",
  "k12-fixed-bollard": "K12 Fixed Bollard",
  "k12-auto-bollard": "K12 Auto Bollard",
  "k12-dab": "K12 Drop Arm Barrier",
  "road-hump": "Road Hump",
  "traffic-light": "Traffic Light",
  "sliding-bollard": "Sliding Bollard",
  "non-crash-barrier": "Non-Crash Barrier",
  "auto-bollard": "Auto Bollard",
  "crash-barrier": "Crash Barrier",
};
